[package]
name = "MarathonRust"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

[dependencies]
valence = { git = "https://github.com/valence-rs/valence" }
rand = "0.8.5"
tracing-subscriber = "0.3.16"

