[package]
name = "marathon_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
valence = { git = "https://github.com/valence-rs/valence" }
valence_anvil = { git = "https://github.com/valence-rs/valence", features = ["valence"] }
rand = "0.8.5"
tracing-subscriber = "0.3.16"
redis = "0.22.1"